/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Racket = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Float64,
  'inStock' : IDL.Bool,
  'balance' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'power' : IDL.Int,
  'price' : IDL.Float64,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : IDL.Int,
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const DrillDifficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const TrainingDrill = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'difficulty' : DrillDifficulty,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const MatchStatus = IDL.Variant({
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const MatchStats = IDL.Record({
  'status' : MatchStatus,
  'player' : IDL.Text,
  'score' : IDL.Text,
  'setScores' : IDL.Vec(IDL.Text),
  'opponent' : IDL.Text,
});
export const Tip = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRacket' : IDL.Func([Racket], [], []),
  'deleteRacket' : IDL.Func([IDL.Nat], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllDrills' : IDL.Func([], [IDL.Vec(TrainingDrill)], ['query']),
  'getAllMatches' : IDL.Func([], [IDL.Vec(MatchStats)], ['query']),
  'getAllRackets' : IDL.Func([], [IDL.Vec(Racket)], ['query']),
  'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedMatches' : IDL.Func([], [IDL.Vec(MatchStats)], ['query']),
  'getCurrentMatches' : IDL.Func([], [IDL.Vec(MatchStats)], ['query']),
  'getDrill' : IDL.Func([IDL.Nat], [TrainingDrill], ['query']),
  'getDrillsByDifficulty' : IDL.Func(
      [DrillDifficulty],
      [IDL.Vec(TrainingDrill)],
      ['query'],
    ),
  'getRacket' : IDL.Func([IDL.Nat], [Racket], ['query']),
  'getRandomTip' : IDL.Func([], [Tip], ['query']),
  'getTip' : IDL.Func([IDL.Nat], [Tip], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateRacket' : IDL.Func([Racket], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Racket = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Float64,
    'inStock' : IDL.Bool,
    'balance' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'power' : IDL.Int,
    'price' : IDL.Float64,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : IDL.Int,
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const DrillDifficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const TrainingDrill = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'difficulty' : DrillDifficulty,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const MatchStatus = IDL.Variant({
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const MatchStats = IDL.Record({
    'status' : MatchStatus,
    'player' : IDL.Text,
    'score' : IDL.Text,
    'setScores' : IDL.Vec(IDL.Text),
    'opponent' : IDL.Text,
  });
  const Tip = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRacket' : IDL.Func([Racket], [], []),
    'deleteRacket' : IDL.Func([IDL.Nat], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllDrills' : IDL.Func([], [IDL.Vec(TrainingDrill)], ['query']),
    'getAllMatches' : IDL.Func([], [IDL.Vec(MatchStats)], ['query']),
    'getAllRackets' : IDL.Func([], [IDL.Vec(Racket)], ['query']),
    'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedMatches' : IDL.Func([], [IDL.Vec(MatchStats)], ['query']),
    'getCurrentMatches' : IDL.Func([], [IDL.Vec(MatchStats)], ['query']),
    'getDrill' : IDL.Func([IDL.Nat], [TrainingDrill], ['query']),
    'getDrillsByDifficulty' : IDL.Func(
        [DrillDifficulty],
        [IDL.Vec(TrainingDrill)],
        ['query'],
      ),
    'getRacket' : IDL.Func([IDL.Nat], [Racket], ['query']),
    'getRandomTip' : IDL.Func([], [Tip], ['query']),
    'getTip' : IDL.Func([IDL.Nat], [Tip], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateRacket' : IDL.Func([Racket], [], []),
  });
};

export const init = ({ IDL }) => { return []; };