/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedAt' : bigint,
  'author' : string,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export type DrillDifficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface MatchStats {
  'status' : MatchStatus,
  'player' : string,
  'score' : string,
  'setScores' : Array<string>,
  'opponent' : string,
}
export type MatchStatus = { 'live' : null } |
  { 'completed' : null };
export interface Racket {
  'id' : bigint,
  'weight' : number,
  'inStock' : boolean,
  'balance' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : string,
  'power' : bigint,
  'price' : number,
}
export interface Tip { 'id' : bigint, 'question' : string, 'answer' : string }
export interface TrainingDrill {
  'id' : bigint,
  'duration' : bigint,
  'difficulty' : DrillDifficulty,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRacket' : ActorMethod<[Racket], undefined>,
  'deleteRacket' : ActorMethod<[bigint], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllDrills' : ActorMethod<[], Array<TrainingDrill>>,
  'getAllMatches' : ActorMethod<[], Array<MatchStats>>,
  'getAllRackets' : ActorMethod<[], Array<Racket>>,
  'getAllTips' : ActorMethod<[], Array<Tip>>,
  'getBlogPost' : ActorMethod<[bigint], BlogPost>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedMatches' : ActorMethod<[], Array<MatchStats>>,
  'getCurrentMatches' : ActorMethod<[], Array<MatchStats>>,
  'getDrill' : ActorMethod<[bigint], TrainingDrill>,
  'getDrillsByDifficulty' : ActorMethod<
    [DrillDifficulty],
    Array<TrainingDrill>
  >,
  'getRacket' : ActorMethod<[bigint], Racket>,
  'getRandomTip' : ActorMethod<[], Tip>,
  'getTip' : ActorMethod<[bigint], Tip>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateRacket' : ActorMethod<[Racket], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];